default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # window need host, masOS should cmt line 6
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: learn_rails_development

test:
  <<: *default
  database: learn_rails_test

production:
  <<: *default
  database: learn_rails_production
  username: learn_rails
  password: <%= ENV['LEARN_RAILS_DATABASE_PASSWORD'] %>
